# Generated by Django 5.0.4 on 2024-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_url', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('votes', models.PositiveIntegerField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
